### PR TITLE
add barcelona madrid's metro support

### PR DESCRIPTION
**Pull request by PassionPenguin**
Cercanías will be added later

### CODE REVIEW

**Comment by PassionPenguin** [comment]
source madrid: https://zh.wikipedia.org/wiki/%E9%A9%AC%E5%BE%B7%E9%87%8C%E5%9C%B0%E9%93%81
source barcelona: https://zh.wikipedia.org/wiki/%E5%B7%B4%E5%A1%9E%E7%BD%97%E9%82%A3%E5%9C%B0%E9%93%81

**Comment by wongchito** [comment]
Please check if you have picked the correct colour. 

We accept the following sources:

1. Official colour or design standards
2. Official map (PDF) 
3. Wikipedia templates
4. Original file (SVG) of images from Wikipedia

Take Line 1 of Madrid as an example, you should

1.  Consider picking colour from the [official map](https://www.metromadrid.es/sites/default/files/documentos/Viaja%20en%20Metro/Planos/Planoesquematico.pdf) in e.g. Adobe Illustrator. The colour of Line 1 should be `#36B3E6`. 

Screenshot 2020-04-01 at 20 35 05

2. Consider using the colour defined in the [original file of images from Wikipedia](https://upload.wikimedia.org/wikipedia/commons/7/76/Madrid-MetroLinea1.svg). The colour of Line 1 in this case should be `#30a3dc`. 

Screenshot 2020-04-01 at 20 42 16

**Comment by PassionPenguin** [comment]
picked via Chrome's inspector instead of viewing the svgs...

**Comment by PassionPenguin** [comment]
will fix it after

**Comment by wongchito** [comment]
Please note that the first approach in the example above is preferred.

**Comment by wongchito** [comment]
Added in 77121de and ed8341f

**Pull request closed without merging**
