### PR TITLE
#125 Download all stations and directions in batch

### PR DESCRIPTION
**Pull request by thekingofcity**
This is a rework on #125 which should fix fonts and `bbox` issues even after the dialog is closed after a `dispatch`.

A drawback that load fonts for every station seems inevitable as `mtr-helper` only looks for fonts appears in the current svg?

Also, would you like to see the zip feature implemented in this PR?

### CODE REVIEW

**Comment by wongchito** [comment]
Some testing results:

- Chrome on macOS:
  - MTR download one:
    - Destination Sign: Working as expected
    - Rail Map: Chinese characters are completely missing if there's too many characters to be rendered. (Template: Guangzhou Line 3)
  - MTR download all:
    - Destination Sign: No points to do this as destination is the almost always the same
    - Rail Map: Working as expected
  - GZMTR download one: Working as expected
  - GZMTR download all:
    - Running-in: BBox is calculated for the previous station not the current one. 
      (Hypothesis: Update current station -> downloading triggered -> calculate BBox)

- Safari on macOS: MTR fonts are not rendered as expected even before clicking download. This may need be be fixed after this PR.

**Comment by thekingofcity** [comment]
> MTR / Rail Map: Chinese characters are completely missing if there's too many characters to be rendered.

Will look into this later.

> GZMTR / Running-in: BBox is calculated for the previous station not the current one.

I tried adding `await new Promise(r => setTimeout(r, 1000));` between the `dispatch` and `download`. But it won't work either.

**Comment by wongchito** [comment]
> > MTR / Rail Map: Chinese characters are completely missing if there's too many characters to be rendered.
> 
> Will look into this later.

Sorry my bad. I turned on "disabling cached" in my Chrome console. Turning it off resolves the issue.

**Comment by thekingofcity** [comment]
Great, then only `bbox` blocks this PR.

**Comment by thekingofcity** [comment]
Looks like the `bbox` will only fail to work in `gzmtr`. How about disabling the batch download for it temporarily?

**Comment by wongchito** [comment]
> Looks like the `bbox` will only fail to work in batch download in `gzmtr`. How about disabling the batch download for `gzmtr` temporarily?
> 
> 

I don't have objection on this.

**Comment by thekingofcity** [comment]
I removed the recursive call and add zip support to the batch download.

Though it was tested in several templates, it would be better if you could test it for another round.

UAT is released with `3.10.11.issue-125-Download-all-stations-and-directions-in-batch.3944435`

**Comment by wongchito** [comment]
Approved.

**Comment by thekingofcity** [comment]
> Btw package urls in package-lock.json are gone again. Let it be fixed by build agent then😀

No problem.

**Pull request merged**
